spring:
  application:
    name: sample-server
server:
  port: 8071
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:8070/eureka/
    
   
  
  